name: helloGithubAction

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: 4. 파이썬 파일 실행
        run: python test.py
      - name: 5. 파이썬 파일 찾기
        run: find / -name 'test.py'
